
spring:
  mail:
    host: smtp2go.com
    #host: smtp.mailersend.net
    port: 587
    #username: MS_ROESWe@test-eqvygm09vv5l0p7w.mlsender.net
    #password: mssp.gOGxn89.3z0vklokjdp47qrx.Soucdzs
    username: async-notify-v1
    password: o53VB[qPjFFAH+zFM/N.5Jarqx4UIBa9UrweG#?bgi?xy3uI+x
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  mail:
    #from: notificaciones@test-eqvygm09vv5l0p7w.mlsender.net
    from: devops@streampayments.io
