apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-notification-service-v1
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-notification-service-v1
  template:
    metadata:
      labels:
        app: ms-notification-service-v1
    spec:
      containers:
        - name: ms-notification-service-v1
          image: servitekcloud.azurecr.io/ms-notification-service-v1:latest  # ser√° sustituida por el tag SHA
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi