apiVersion: v1
kind: Service
metadata:
  name: ms-notification-service-v1
  namespace: default
spec:
  selector:
    app: ms-notification-service-v1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer